Update check-installation.yml

diff --git a/.github/workflows/check-installation.yml b/.github/workflows/check-installation.yml
--- a/.github/workflows/check-installation.yml
+++ b/.github/workflows/check-installation.yml
@@ -1,8 +1,8 @@
 name: Test Chirpity Compilation
 run-name: ${{ github.actor }} is installing chirpity
-on: [push]
+on: [push,  workflow_dispatch]
 jobs:
-  Explore-GitHub-Actions:
+  Build-Windows:
     runs-on: windows-latest
     steps:
       - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
@@ -18,7 +18,23 @@ jobs:
         with:
             node-version: 20.0.x
       - run: echo "🍏 Node setup status is ${{ job.status }}."
-      - name: Install
-        run: npm install
-      - run: echo "Install's status is ${{ job.status }}."
+      - name: Install dependencies
+        run: |
+          npm install
+          echo "Install's status is ${{ job.status }}."
+      - name: Build
+        run: electron-builder --win --x64 
+      - name: Check installer exists
+        run: |
+          # Retrieve the version from package.json
+          VERSION=$(jq -r '.version' package.json)
+          # Construct the filename
+          FILENAME="chirpity Setup-$VERSION.exe"
+          # Check if the file exists
+          if [ -f "./dist/$FILENAME" ]; then
+            echo "Executable $FILENAME found in ./dist"
+          else
+            echo "Executable $FILENAME not found in ./dist" && exit 1
+          fi
+      - run: echo "File check status is ${{ job.status }}."
 
